<?php

return [
    // Format: 'module' => ['OFFICE' => ['Name 1', 'Name 2']]
    'oil' => [
        'SUN' => [
            'Ramanda',
            'Agus Prawitno Sitohang',
            'Rizky Setiawan',
            'Andri Kaswari',
            'Dedi Prastiawan',
            'Ahmad Prawira Putra Pohan',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko'
        ],
        'YBS' => ['Arif Rahman', 'Asral', 'WEWEN SAPUTRA', 'MUHAMMAD SAFII', 'SAS FEGO RIKANDOKA', 'FIKRI HIDAYAT', 'ARIF RAHMAN', 'GABE HAMORAON', 'Fitrah Prabowo', 'Raynaldy', 'Rizki Ardian Sinaga', 'Sas Fego Rikandoka', 'Taufiq'],
        'SJN' => [],
    ],
    'kernel' => [
        'YBS' => [
            'ARDI GHRAFANAKA',
            'ARIF RAHMAN',
            'ASRAL',
            'EKI PUTRA',
            'FEBRI',
            'Fitra',
            'HARIZON',
            'Hafiz',
            'IRVAN ROYNALDI',
            'RAMBI',
            'RIAN IDRIS',
            'RIDWAN',
            "RIZKI ARDIAN SINAGA",
            'WIRA CANDRA'
        ],
        'SUN' => [
            'Ramanda',
            'Andri Kaswari',
            'Diki Apriadi Nasution',
            'Jovyel Romatuah Silaen',
            'Apriandi',
            'Sarianda',
            'Muhammad Zainuddin Siagian',
            'Roy Vandi Haviki',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko'
        ],
        'SJN' => [],
    ],
    'dirt_moist' => [
        'YBS' => [
            'ARDI GHRAFANAKA',
            'ARIF RAHMAN',
            'ASRAL',
            'EKI PUTRA',
            'FEBRI',
            'Fitra',
            'HARIZON',
            'IRVAN ROYNALDI',
            'RAMBI',
            'RIAN IDRIS',
            'RIDWAN',
            "RIZKI ARDIAN SINAGA",
            'WIRA CANDRA'
        ],
        'SUN' => [
            'Ramanda',
            'Andri Kaswari',
            'Diki Apriadi Nasution',
            'Jovyel Romatuah Silaen',
            'Apriandi',
            'Sarianda',
            'Muhammad Zainuddin Siagian',
            'Roy Vandi Haviki',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko'
        ],
        'SJN' => [],
    ],
    'qwt' => [
        'YBS' => [
            'ARDI GHRAFANAKA',
            'ARIF RAHMAN',
            'ASRAL',
            'EKI PUTRA',
            'FEBRI',
            'Fitra',
            'HARIZON',
            'IRVAN ROYNALDI',
            'RAMBI',
            'RIAN IDRIS',
            'RIDWAN',
            "RIZKI ARDIAN SINAGA",
            'WIRA CANDRA'
        ],
        'SUN' => [
            'Ramanda',
            'Andri Kaswari',
            'Diki Apriadi Nasution',
            'Jovyel Romatuah Silaen',
            'Apriandi',
            'Sarianda',
            'Muhammad Zainuddin Siagian',
            'Roy Vandi Haviki',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko'
        ],
        'SJN' => [],
    ],
    'ripple_mill' => [
        'YBS' => [
            'ARDI GHRAFANAKA',
            'ARIF RAHMAN',
            'ASRAL',
            'EKI PUTRA',
            'FEBRI',
            'Fitra',
            'HARIZON',
            'IRVAN ROYNALDI',
            'RAMBI',
            'RIAN IDRIS',
            'RIDWAN',
            "RIZKI ARDIAN SINAGA",
            'WIRA CANDRA'
        ],
        'SUN' => [
            'Ramanda',
            'Andri Kaswari',
            'Diki Apriadi Nasution',
            'Jovyel Romatuah Silaen',
            'Apriandi',
            'Sarianda',
            'Muhammad Zainuddin Siagian',
            'Roy Vandi Haviki',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko'
        ],
        'SJN' => [],
    ],
    'destoner' => [
        'YBS' => [
            'ARDI GHRAFANAKA',
            'ARIF RAHMAN',
            'ASRAL',
            'EKI PUTRA',
            'FEBRI',
            'Fitra',
            'HARIZON',
            'IRVAN ROYNALDI',
            'RAMBI',
            'RIAN IDRIS',
            'RIDWAN',
            "RIZKI ARDIAN SINAGA",
            'WIRA CANDRA'
        ],
        'SUN' => [
            'Ramanda',
            'Andri Kaswari',
            'Diki Apriadi Nasution',
            'Jovyel Romatuah Silaen',
            'Apriandi',
            'Sarianda',
            'Muhammad Zainuddin Siagian',
            'Roy Vandi Haviki',
            'Andrian Pranata',
            'Mei Shandy Dwi Putra',
            'Setia Ardi ',
            'Rohmania Budi Nantoko'
        ],
        'SJN' => [],
    ],
];
